bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static


urlpatterns = [
    path('', RedirectView.as_view(url='/account/')),
    path('images/', include('images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests


class ImageCreateForm(forms.ModelForm):
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.\n'
                                        'Valid extensions include ' + valid_extensions + '.')
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        # Why recreate the slug? Isn't there a defined slug
        name = slugify(image.title)
        # attribute already? Try using image.slug instead.
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from the given URL
        response = requests.get(image_url)
        image.image.save(image_name, ContentFile(response.content), save=False)
        if commit:
            image.save()
        return image

    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput
        }

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from comments.models import Comment
from comments.forms import CommentForm
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.contrib.contenttypes.models import ContentType
from actions.utils import create_action
import redis
from django.conf import settings
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Connect to redis
if settings.USE_REDIS:
    r = redis.Redis(host=settings.REDIS_HOST,
                    port=settings.REDIS_PORT,
                    db=settings.REDIS_DB)
else:
    r = False


def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            # If AJAX request and page out of range
            #  return an empty page.
            return HttpResponse('')
        # If page out of range return last page of results
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(request,
                      'images/image/list_images.html',
                      {'section': 'images', 'images': images})
    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images})


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    comments = Comment.objects.filter(target_id=id)
    if r:
        total_views = r.incr(f'image:{image.id}:views')
        r.zincrby('image_ranking', 1, image.id)
    else:
        total_views = None

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            # Set the values of target_id, target_ct, and poster
            form.instance.target_id = id
            form.instance.target_ct = ContentType.objects.get(
                app_label='images', model='image')
            # Assuming the poster is the currently logged-in user
            form.instance.poster = request.user
            form.save()
            create_action(request.user, 'commented on',
                          Image.objects.get(id=id))
            messages.success(
                request, f'Comment posted successfully!')

    form = CommentForm()

    return render(request,
                  'images/image/detail.html',
                  {'section': 'images', 'image': image,
                   'total_views': total_views,
                   'comments': comments,
                   'form': form})


@login_required
def image_create(request):
    if request.method == 'POST':
        # Form has been sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request, 'Image added successfully')
            return redirect(new_image.get_absolute_url())

    else:
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html',
                  {'section': 'images', 'form': form})


@login_required
def image_ranking(request):
    if r:
        image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
        image_ranking_ids = [int(id) for id in image_ranking]
        most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
        most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    else:
        most_viewed = None
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images', 'most_viewed': most_viewed})

images/templates/images/image/create.html
{% extends 'base.html' %}
{% block title %}Bookmark an Image{% endblock %}
{% block content %}
<h1>Bookmark an image</h1>
<img src='{{request.GET.url}}' class ='image-preview'>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type='submit' value='Bookmark it!'>
</form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}
  <a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
  </a>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        {% if total_views %}
        <span class="count">
          {{total_views}} view{{total_views|pluralize}}
        </span>
        {% endif %}
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
    class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class='container'>
    <div class="image-likes">
      {% for user in users_like %}
        <div>
            {% if user.profile.photo %}
             {% thumbnail user.profile.photo "80x80" crop="100%" as im %}
             <a href="{{user.get_absolute_url}}">
                <img src="{{im.url}}" alt="{{user.get_full_name}}" class='item-img'>
            </a>
            {% else %}
            <a href="{{user.get_absolute_url}}">
                {% thumbnail 'static/default.jpg' "80x80" crop="100%" as im %}
                <img src="{{im.url}}" alt="{{user.get_full_name}} has no profile picture" class='item-img'>
            </a>
            {% endif %}
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
<div class='comment-section'>
  <hr>
<h3>Comments ({{comments.count}})</h3>
{% if comments %}
<div id='comment-list'>
    {% for comment in comments %}
     {% include 'comments/comment/detail.html' %}
    {% endfor %}
{% else %}
</div>
<p>Nobody has commented yet.</p>
{% endif %}
</div>
{% if user.is_authenticated %}
<div class='comment-post'>
{% include "comments/comment/post_comment.html" %}
</div>
{% endif %}
</div>
{% endblock %}

{% block domready %}
  const url = '{% url "images:like" %}';
  var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }

  document.querySelector('a.like')
          .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;

    // add request body
    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;

    // send HTTP request
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
      if (data['status'] === 'ok')
      {
        var previousAction = likeButton.dataset.action;

        // toggle button text and data-action
        var action = previousAction === 'like' ? 'unlike' : 'like';
        likeButton.dataset.action = action;
        likeButton.innerHTML = action;

        // update like count
        var likeCount = document.querySelector('span.count .total');
        var totalLikes = parseInt(likeCount.innerHTML);
        likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
      }
    })
  });
{% endblock %}

images/templates/images/image/list.html
{% extends 'base.html' %}
{% block title %}Images LegallyDistinctFromPinterest'sPinFeature'd{% endblock %}
{%block content%}
<h1>Images LegallyDistinctFromPinterest'sPinFeature'd</h1>
<div id='image-list'>
    {% include "images/image/list_images.html"%}
</div>
{% endblock %}
{% block domready %}
var page = 1
var emptyPage = false
var blockRequest = false

window.addEventListener('scroll',function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if (window.pageYOffset > margin && !emptyPage && !blockRequest){
        blockRequest = true;
        page += 1

        fetch('?images_only=1&page=' + page)
        .then(response => response.text())
        .then(html => {
            if(html ===''){
                emptyPage = true;
            }
            else{
                var imageList = document.getElementById('image-list');
                imageList.insertAdjacentHTML('beforeEnd',html);
                blockRequest=false;
            }
        })
    }
});

// Launch scroll event
const scrollEvent = new Event('scroll');
window.dispatchEvent(scrollEvent);
{% endblock %}

images/templates/images/image/list_images.html
{% load thumbnail %}
{% for image in images %}
<div class ="image">
    <a href="{{image.get_absolute_url}}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{image.get_absolute_url}}">
            <img src="{{im.url}}">
        </a>
    </a>
    <div class = "info">
        <a href = "{{ image.get_absolute_url}}" class = 'title'>
            {{image.title}}
        </a>
    </div>
</div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends 'base.html' %}
{% block title %}Images Ranking{% endblock %}

{% block content %}
<h1>Images Ranking</h1>
<ol>
    {% for image in most_viewed %}
     <li>
        <a href="{{image.get_absolute_url}}">
            {{image.title}}
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}